arbitrary commit for draft PR
story-squad/clash-api-node pull request #173
Opened 2022-06-10 19:19 UTC by Bus42

Implementation of Auth0

2022-06-13 13:28 UTC, jduell12 requested changes
It seems like there's more changes than just the env sample and README. They look like changes that were made on and pushed to WIP2. So make sure to rebase with WIP2 or edit the commits and only select the env sample and README files to commit in this PR

2022-06-13 13:28 UTC, jduell12 commented on README.md
> +### Set up pgAdmin
Do you need to download PostgreSQL before pgAdmin or does it download for you?

2022-06-13 19:16 UTC, Bus42 commented on README.md
> +### Set up pgAdmin
Yes, you do need it before pgAdmin, I will include that in the README. Thank you for catching that.

2022-06-13 19:21 UTC, Bus42 commented on README.md
> +### Set up pgAdmin
The other file changes were due to running `npm lint`, fixing the import of GamesModel (it was spelled gamesModel), and installing the necessary packages for auth0 (auth0 and openIdConnect)

2022-06-14 17:18 UTC, jduell12 requested changes

2022-06-14 17:18 UTC, jduell12 commented on src/api/middlewares/checkJwt.js
> +const jwtCheck = jwt({
This can go in the jwtHandler or if we want to keep it separate we can rename this middleware to checkAuth0Jwt or something along those lines.

2022-06-14 17:18 UTC, jduell12 commented on src/api/middlewares/submissionHandler.js
> +// const mmm = require('mmmagic');
These can be removed completely since we're going with a different package due to incompatibility with many developer's local settings

2022-06-14 17:18 UTC, jduell12 commented on src/api/middlewares/submissionHandler.js
> +    // const magic = new Magic(mmm.MAGIC_MIME_TYPE);
Same as above

2022-06-15 13:18 UTC, jduell12 approved these changes

2022-06-15 13:20 UTC, merged